2023-02-10 11:58:53,635 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 11:59:53,853 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:00:54,117 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:01:54,339 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:02:54,632 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:03:54,851 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:04:55,069 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:05:55,295 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 383675606196979292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 746, in get_single_value
    val = frappe.qb.engine.get_query(
  File "apps/frappe/frappe/database/query.py", line 513, in get_query
    criterion = self.build_conditions(table, filters, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 369, in build_conditions
    criterion = self.dict_query(filters=filters, table=table, **kwargs)
  File "apps/frappe/frappe/database/query.py", line 328, in dict_query
    _operator = self.OPERATOR_MAP["="]
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "apps/frappe/frappe/database/query.py", line 194, in OPERATOR_MAP
    if frappe.get_hooks("filters_config"):
  File "apps/frappe/frappe/__init__.py", line 1476, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1441, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(sort=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1408, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 938, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 942, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 958, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 218, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 76, in execute_query
    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 188, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 94, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 100, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user '_5d11548d6c1cccf4'@'localhost'")

2023-02-10 12:06:55,777 ERROR scheduler Exception in Enqueue Events for Site verticals.knestcrm.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 76, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 113, in is_scheduler_inactive
    if is_scheduler_disabled():
  File "apps/frappe/frappe/utils/scheduler.py", line 125, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 753, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "apps/frappe/frappe/__init__.py", line 1207, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 65, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 123, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 129, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 148, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType System Settings not found

