Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 123, in init_request
    raise frappe.SessionStopped("Session Stopped")
frappe.exceptions.SessionStopped: Session Stopped

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 112, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "apps/frappe/frappe/__init__.py", line 1516, in setup_module_map
    for module in get_module_list(app):
  File "apps/frappe/frappe/__init__.py", line 1374, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'india_compliance'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 112, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "apps/frappe/frappe/__init__.py", line 1516, in setup_module_map
    for module in get_module_list(app):
  File "apps/frappe/frappe/__init__.py", line 1374, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'india_compliance'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 112, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "apps/frappe/frappe/__init__.py", line 1516, in setup_module_map
    for module in get_module_list(app):
  File "apps/frappe/frappe/__init__.py", line 1374, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'india_compliance'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 112, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "apps/frappe/frappe/__init__.py", line 1516, in setup_module_map
    for module in get_module_list(app):
  File "apps/frappe/frappe/__init__.py", line 1374, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'india_compliance'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 112, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "apps/frappe/frappe/__init__.py", line 1516, in setup_module_map
    for module in get_module_list(app):
  File "apps/frappe/frappe/__init__.py", line 1374, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'india_compliance'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 132, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 68, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 108, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 133, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 248, in authenticate
    self.fail("Invalid login credentials", user=user.name)
  File "apps/frappe/frappe/auth.py", line 291, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 132, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 68, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 108, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 133, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 248, in authenticate
    self.fail("Invalid login credentials", user=user.name)
  File "apps/frappe/frappe/auth.py", line 291, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 132, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 68, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 108, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 133, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 233, in authenticate
    self.fail(_("Incomplete login details"), user=user)
  File "apps/frappe/frappe/auth.py", line 291, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError

Traceback (most recent call last):
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 132, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 68, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "apps/frappe/frappe/sessions.py", line 305, in resume
    data = self.get_session_record()
  File "apps/frappe/frappe/sessions.py", line 323, in get_session_record
    r = self.get_session_data()
  File "apps/frappe/frappe/sessions.py", line 337, in get_session_data
    data = self.get_session_data_from_cache()
  File "apps/frappe/frappe/sessions.py", line 355, in get_session_data_from_cache
    self._delete_session()
  File "apps/frappe/frappe/sessions.py", line 393, in _delete_session
    delete_session(self.sid, reason="Session Expired")
  File "apps/frappe/frappe/sessions.py", line 108, in delete_session
    logout_feed(user, reason)
  File "apps/frappe/frappe/core/doctype/activity_log/feed.py", line 61, in logout_feed
    add_authentication_log(subject, user, operation="Logout")
  File "apps/frappe/frappe/core/doctype/activity_log/activity_log.py", line 43, in add_authentication_log
    frappe.get_doc(
  File "apps/frappe/frappe/model/document.py", line 266, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
  File "apps/frappe/frappe/model/base_document.py", line 498, in db_insert
    frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 213, in sql
    raise frappe.QueryDeadlockError(e) from e
frappe.exceptions.QueryDeadlockError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

Traceback (most recent call last):
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 132, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 68, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "apps/frappe/frappe/auth.py", line 205, in make_session
    frappe.local.session_obj = Session(
  File "apps/frappe/frappe/sessions.py", line 238, in __init__
    self.resume()
  File "apps/frappe/frappe/sessions.py", line 305, in resume
    data = self.get_session_record()
  File "apps/frappe/frappe/sessions.py", line 323, in get_session_record
    r = self.get_session_data()
  File "apps/frappe/frappe/sessions.py", line 339, in get_session_data
    data = self.get_session_data_from_db()
  File "apps/frappe/frappe/sessions.py", line 387, in get_session_data_from_db
    self._delete_session()
  File "apps/frappe/frappe/sessions.py", line 393, in _delete_session
    delete_session(self.sid, reason="Session Expired")
  File "apps/frappe/frappe/sessions.py", line 108, in delete_session
    logout_feed(user, reason)
  File "apps/frappe/frappe/core/doctype/activity_log/feed.py", line 61, in logout_feed
    add_authentication_log(subject, user, operation="Logout")
  File "apps/frappe/frappe/core/doctype/activity_log/activity_log.py", line 43, in add_authentication_log
    frappe.get_doc(
  File "apps/frappe/frappe/model/document.py", line 266, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
  File "apps/frappe/frappe/model/base_document.py", line 498, in db_insert
    frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 213, in sql
    raise frappe.QueryDeadlockError(e) from e
frappe.exceptions.QueryDeadlockError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

