Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:22:48 home-ubuntu-frappe-bench:long: Job OK (f09c4694-9465-4020-9955-0b6f91e156ae)
06:22:48 Result is kept for 600 seconds
06:22:48 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.stock.doctype.repost_item_valuation.repost_item_valua..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (0aa2c2cf-e13a-4e43-bccd-0a63a50ed9d6)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:22:48 home-ubuntu-frappe-bench:long: Job OK (0aa2c2cf-e13a-4e43-bccd-0a63a50ed9d6)
06:22:48 Result is kept for 600 seconds
06:23:48 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.bulk_transaction.doctype.bulk_transaction_log.bulk_tr..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (032a41db-9a96-4502-92ea-0fff1e76fac2)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:23:48 home-ubuntu-frappe-bench:long: Job OK (032a41db-9a96-4502-92ea-0fff1e76fac2)
06:23:48 Result is kept for 600 seconds
06:23:48 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.stock.doctype.repost_item_valuation.repost_item_valua..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (b7e9706d-f463-487f-9e42-ef92310b86df)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:23:49 home-ubuntu-frappe-bench:long: Job OK (b7e9706d-f463-487f-9e42-ef92310b86df)
06:23:49 Result is kept for 600 seconds
06:24:49 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.bulk_transaction.doctype.bulk_transaction_log.bulk_tr..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (230b1617-2cd2-482e-9c5e-fef6fa2d4e53)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:24:49 home-ubuntu-frappe-bench:long: Job OK (230b1617-2cd2-482e-9c5e-fef6fa2d4e53)
06:24:49 Result is kept for 600 seconds
06:24:49 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.stock.doctype.repost_item_valuation.repost_item_valua..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (1369ae40-ec26-40d7-8561-7dc69e086dcb)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:24:49 home-ubuntu-frappe-bench:long: Job OK (1369ae40-ec26-40d7-8561-7dc69e086dcb)
06:24:49 Result is kept for 600 seconds
06:25:49 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.bulk_transaction.doctype.bulk_transaction_log.bulk_tr..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (ea39acbf-bfe3-4f89-9f08-b5f406d6b20d)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:25:50 home-ubuntu-frappe-bench:long: Job OK (ea39acbf-bfe3-4f89-9f08-b5f406d6b20d)
06:25:50 Result is kept for 600 seconds
06:25:50 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.stock.doctype.repost_item_valuation.repost_item_valua..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (c487d376-9803-4f1b-8552-e205b580c87b)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:25:50 home-ubuntu-frappe-bench:long: Job OK (c487d376-9803-4f1b-8552-e205b580c87b)
06:25:50 Result is kept for 600 seconds
06:26:50 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.bulk_transaction.doctype.bulk_transaction_log.bulk_tr..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (be21a23b-0873-4cc2-9458-587dda3b2a01)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:26:50 home-ubuntu-frappe-bench:long: Job OK (be21a23b-0873-4cc2-9458-587dda3b2a01)
06:26:50 Result is kept for 600 seconds
06:26:50 home-ubuntu-frappe-bench:long: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., kwargs={'job_type': 'erpnext.stock.doctype.repost_item_valuation.repost_item_valua..., method='frappe.core.doctype.scheduled_job_type.scheduled_job_type.run_scheduled_jo..., site='erp.knestcrm.com', user='Administrator') (e7696328-71fa-4368-b109-0ddca24b035f)
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 82, in execute
    self.log_status("Start")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in execute
    self.log_status("Failed")
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 97, in log_status
    frappe.logger("scheduler").info(f"Scheduled Job {status}: {self.method} for {frappe.local.site}")
  File "apps/frappe/frappe/__init__.py", line 2187, in logger
    return get_logger(
  File "apps/frappe/frappe/utils/logger.py", line 72, in get_logger
    site_handler = RotatingFileHandler(sitelog_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: 'sites/erp.knestcrm.com/logs/scheduler.log'

06:26:50 home-ubuntu-frappe-bench:long: Job OK (e7696328-71fa-4368-b109-0ddca24b035f)
06:26:50 Result is kept for 600 seconds
06:27:50 Warm shut down requested
06:27:50 Unsubscribing from channel rq:pubsub:01471fd0192542f9994714317470ec54.ip-172-31-38-26.25594.home-ubuntu-frappe-bench:long
